#!/usr/bin/env python3
"""Generate bounded strict syscall leaves using the recorded per-CPU Linux numbers."""
import argparse
from pathlib import Path
import re
import struct
import subprocess
import tempfile
from gen_memory_fast import functions

ROOT = Path(__file__).resolve().parents[1]
CALLS = ('read', 'write', 'close', 'fcntl', 'accept', 'recvfrom', 'epoll_ctl',
         'epoll_pwait', 'timerfd_settime', 'clock_gettime', 'clone')
DEFINES = CALLS+('exit',)
NAMES = tuple('rt_sys_'+{'recvfrom':'recv', 'epoll_pwait':'epoll_wait'}.get(n,n) for n in CALLS)


def generate():
    result = ['// Generated by tools/gen_syscall_fast.py from tools/arch/syscall-fast-*.S.']
    with tempfile.TemporaryDirectory() as tmp:
        for arch, target in [('arm64', 'aarch64-linux-gnu'), ('amd64', 'x86_64-linux-gnu')]:
            source = (ROOT/f'lib/runtime/syscalls_linux_{arch}.tin').read_text()
            numbers = dict(re.findall(r'fn linux_nr_(\w+)\(\)(?: i64)? \{\s*return (\d+);?\s*\}',source))
            obj = Path(tmp)/f'{arch}.o'
            subprocess.run(['clang', '-target', target,
                *[f'-DNR_{n.upper()}={numbers[n]}' for n in DEFINES], '-c',
                str(ROOT/f'tools/arch/syscall-fast-{arch}.S'), '-o', str(obj)], check=True)
            table = functions(obj, NAMES)
            result += ['', f'fn syscall_fast_{arch}(name str) i64 {{', '\tmut hex = ""']
            for name in NAMES:
                data = table[name]
                code = ''.join(f'{v[0]:08x}' for v in struct.iter_unpack('<I',data)) if arch=='arm64' else data.hex()
                result += [f'\tif name == "{name}" {{', f'\t\thex = "{code}"', '\t}']
            result += ['\tif i64(byte_at(hex, 0)) == 0 {', '\t\treturn 0', '\t}', '\tlet v = []i64{}', '\tmut i = 0',
                       '\tfor i < len(hex) {']
            if arch == 'arm64':
                result += ['\t\traw(cast([]i64, v), hex_word(hex, i))', '\t\ti = i + 8']
            else:
                result += ['\t\tv = append(v, num_digit(i64(hex[i])) * 16 + num_digit(i64(hex[i + 1])))', '\t\ti = i + 2']
            result += ['\t}', '\treturn cast(i64, v)', '}']
    return '\n'.join(result)+'\n'


if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    path=ROOT/'selfhost/syscall_fast.tin'
    result=generate()
    if args.check:
        assert path.read_text()==result, 'syscall leaves are stale'
    else:
        path.write_text(result)
