#!/usr/bin/env python3
"""Generate bounded strict syscall leaves using the recorded per-CPU Linux numbers."""
import argparse
from pathlib import Path
import re
import struct
import subprocess
import tempfile
from gen_memory_fast import functions

ROOT = Path(__file__).resolve().parents[1]
CALLS = ('read', 'write', 'close', 'fcntl', 'accept', 'recvfrom', 'epoll_ctl',
         'epoll_pwait', 'timerfd_settime', 'clock_gettime')
NAMES = tuple('rt_sys_'+{'recvfrom':'recv', 'epoll_pwait':'epoll_wait'}.get(n,n) for n in CALLS)


def generate():
    result = ['// Generated by tools/gen_syscall_fast.py from tools/arch/syscall-fast-*.S.']
    with tempfile.TemporaryDirectory() as tmp:
        for arch, target in [('arm64', 'aarch64-linux-gnu'), ('amd64', 'x86_64-linux-gnu')]:
            source = (ROOT/f'lib/runtime/syscalls_linux_{arch}.tin').read_text()
            numbers = dict(re.findall(r'fn linux_nr_(\w+)\(\) \{ return (\d+); \}',source))
            obj = Path(tmp)/f'{arch}.o'
            subprocess.run(['clang', '-target', target,
                *[f'-DNR_{n.upper()}={numbers[n]}' for n in CALLS], '-c',
                str(ROOT/f'tools/arch/syscall-fast-{arch}.S'), '-o', str(obj)], check=True)
            table = functions(obj, NAMES)
            result += ['', f'fn syscall_fast_{arch}(name) {{', '    let hex="";']
            for name in NAMES:
                data = table[name]
                code = ''.join(f'{v[0]:08x}' for v in struct.iter_unpack('<I',data)) if arch=='arm64' else data.hex()
                result.append(f'    if streq(name,"{name}") {{ hex="{code}"; }}')
            result += ['    if load8(hex) == 0 { return 0; }', '    let v=vec_new(); let i=0;',
                       '    while load8(hex+i) != 0 {']
            if arch == 'arm64':
                result.append('        raw(v,hex_word(hex+i)); i=i+8;')
            else:
                result.append('        vec_push(v,num_digit(load8(hex+i))*16+num_digit(load8(hex+i+1))); i=i+2;')
            result += ['    }', '    return v;', '}']
    return '\n'.join(result)+'\n'


if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    path=ROOT/'selfhost/syscall_fast.tin'
    result=generate()
    if args.check:
        assert path.read_text()==result, 'syscall leaves are stale'
    else:
        path.write_text(result)
