#!/usr/bin/env python3
"""Generate PostgreSQL SASLprep's Unicode 3.2 tables from Python's fixed UCD.
No downloads or third-party modules. Run from any directory; output is deterministic.
RFC 3454/4013 require Unicode 3.2, not the host's current Unicode version.
"""
from pathlib import Path
import stringprep as sp
import unicodedata as ud

U = ud.ucd_3_2_0
ROOT = Path(__file__).resolve().parents[1]


def ranges(test):
    out = []
    start = last = None
    for cp in range(0x110000):
        if test(chr(cp)):
            if start is None:
                start = cp
            last = cp
        elif start is not None:
            out.extend((start, last))
            start = None
    if start is not None:
        out.extend((start, last))
    return out


def array(name, data):
    lines = [f'var {name} = []i64{{']
    for i in range(0, len(data), 18):
        lines.append('\t' + ', '.join(str(n) for n in data[i:i+18]) + ',')
    return '\n'.join(lines) + '\n}\n\n'


def main():
    tables = '// Generated by tools/gen_saslprep.py from Unicode 3.2; do not edit.\npackage sasl\n\nimport "glyph"\n\n'
    prohibited = lambda c: any(f(c) for f in (sp.in_table_a1, sp.in_table_c12, sp.in_table_c21, sp.in_table_c22, sp.in_table_c3, sp.in_table_c4, sp.in_table_c5, sp.in_table_c6, sp.in_table_c7, sp.in_table_c8, sp.in_table_c9))
    for name, f in [('removed', sp.in_table_b1), ('spaces', sp.in_table_c12), ('prohibited', prohibited), ('randal', sp.in_table_d1), ('lcat', sp.in_table_d2)]:
        tables += array(name, ranges(f))
    decomp, chars, combining, compose = [], [], [], []
    for cp in range(0x110000):
        c = chr(cp)
        cc = U.combining(c)
        if cc:
            combining.extend((cp, cc))
        if not 0xac00 <= cp <= 0xd7a3:
            d = U.normalize('NFKD', c)
            if d != c:
                decomp.extend((cp, len(chars), len(d)))
                chars.extend(map(ord, d))
        d = U.decomposition(c).split()
        if len(d) == 2 and not d[0].startswith('<'):
            a, b = (int(x, 16) for x in d)
            if U.normalize('NFC', chr(a)+chr(b)) == c:
                compose.append(((a<<21)|b, cp))
    tables += array('decomp', decomp)+array('chars', chars)+array('combining', combining)
    tables += array('compositions', [v for row in sorted(compose) for v in row])
    runtime = Path(__file__).with_name('saslprep_runtime.tin').read_text()
    (ROOT/'lib/postgres/sasl/sasl.tin').write_text(tables+runtime)


if __name__ == '__main__':
    main()
