#!/usr/bin/env python3
"""Regenerate selfhost/aes_hw.tin, seal's AES-CTR, GHASH and CPU-check leaves, from
tools/arch/aes-gcm-*.S (needs clang). The code generators emit these bytes for the
seal.aes_hw_ctr, seal.aes_hw_subword, seal.ghash_hw and seal.aes_hw_cpu placeholders."""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile
from gen_memory_fast import functions

ROOT = Path(__file__).resolve().parents[1]
NAMES = {'arm64': ('aes_hw_ctr', 'aes_hw_subword', 'ghash_hw'), 'amd64': ('aes_hw_cpu', 'aes_hw_ctr', 'aes_hw_subword', 'ghash_hw')}


def generate():
    text = ['// Generated by tools/gen_aes_hw.py from tools/arch/aes-gcm-*.S.']
    with tempfile.TemporaryDirectory() as tmp:
        for arch, target in [('arm64', 'aarch64-linux-gnu'), ('amd64', 'x86_64-linux-gnu')]:
            obj = Path(tmp)/f'{arch}.o'
            subprocess.run(['clang', '-target', target, '-c', str(ROOT/f'tools/arch/aes-gcm-{arch}.S'), '-o', str(obj)], check=True)
            table = functions(obj, NAMES[arch])
            text += ['', f'// aes_hw_{arch} is the machine code of seal.NAME (NAME without the package), or 0.',
                     f'fn aes_hw_{arch}(name str) i64 {{', '\tmut hex = ""']
            for name in NAMES[arch]:
                data = table[name]
                if arch == 'arm64':
                    data = ''.join(f'{v[0]:08x}' for v in struct.iter_unpack('<I', data))
                else:
                    data = data.hex()
                text += [f'\tif name == "seal.{name}" {{', f'\t\thex = "{data}"', '\t}']
            text += ['\tif len(hex) == 0 {', '\t\treturn 0', '\t}', '\tlet v = []i64{}', '\tmut i = 0', '\tfor i < len(hex) {']
            if arch == 'arm64':
                text += ['\t\traw(cast([]i64, v), hex_word(hex, i))', '\t\ti = i + 8']
            else:
                text += ['\t\tv = append(v, num_digit(i64(hex[i])) * 16 + num_digit(i64(hex[i + 1])))', '\t\ti = i + 2']
            text += ['\t}', '\treturn cast(i64, v)', '}']
    return '\n'.join(text)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT/'selfhost/aes_hw.tin'
    result = generate()
    if args.check:
        assert path.read_text() == result, 'AES machine code is stale'
    else:
        path.write_text(result)
