#!/usr/bin/env python3
"""Generate lib/glyph/tables.tin and lib/runtime/printable.tin from Go's unicode/tables.go (run from the
repo root).

    python3 tools/gen_unicode.py [GOROOT/src/unicode/tables.go]

The tables are the Unicode Character Database as Go ships it: general categories, scripts,
properties, case ranges and the case orbit. Each range table is packed into one string constant,
8 bytes per range (low, high: 3 bytes each, little endian; stride: 2 bytes), so a binary links
them as read-only data and starts without running any initializer. The runtime cannot import glyph, so
it gets its own copy of one set, the printable runes (categories L, M, N, P and S), as merged runs.
"""
import os
import re
import subprocess
import sys

OUT = "lib/glyph/tables.tin"
OUT_PRINT = "lib/runtime/printable.tin"


def default_source():
    root = subprocess.run(["go", "env", "GOROOT"], capture_output=True, text=True, check=True).stdout.strip()
    return os.path.join(root, "src", "unicode", "tables.go")


def parse(path):
    text = open(path, encoding="utf-8").read()
    version = re.search(r'Version = "([^"]+)"', text).group(1)
    tables = {}
    for m in re.finditer(r"^var (_\w+) = &RangeTable\{\n(.*?)^\}\n", text, re.S | re.M):
        body = m.group(2)
        ranges = [tuple(int(x, 16) if x.startswith("0x") else int(x) for x in r)
                  for r in re.findall(r"\{(0x[0-9a-fA-F]+|\d+), (0x[0-9a-fA-F]+|\d+), (0x[0-9a-fA-F]+|\d+)\}", body)]
        tables[m.group(1)] = ranges
    alias = dict(re.findall(r"^\t(\w+)\s+= (_\w+)", text, re.M))

    def named(var):
        m = re.search(r"^var %s = map\[string\]\*RangeTable\{\n(.*?)^\}\n" % var, text, re.S | re.M)
        out = {}
        for key, ident in re.findall(r'"(\w+)":\s+(\w+),', m.group(1)):
            out[key] = tables[alias.get(ident, ident)]
        return out

    cats, scripts, props = named("Categories"), named("Scripts"), named("Properties")
    m = re.search(r"^var _CaseRanges = \[\]CaseRange\{\n(.*?)^\}\n", text, re.S | re.M)
    cases = []
    for lo, hi, a, b, c in re.findall(r"\{(0x\w+), (0x\w+), d\{([^,]+), ([^,]+), ([^}]+)\}\}", m.group(1)):
        def delta(s):
            s = s.strip()
            return 0x110000 if s == "UpperLower" else int(s)
        cases.append((int(lo, 16), int(hi, 16), delta(a), delta(b), delta(c)))
    m = re.search(r"^var caseOrbit = \[\]foldPair\{\n(.*?)^\}\n", text, re.S | re.M)
    orbit = [(int(a, 16), int(b, 16)) for a, b in re.findall(r"\{(0x\w+), (0x\w+)\}", m.group(1))]
    return version, cats, scripts, props, cases, orbit


def literal(data):
    out = []
    for b in data:
        c = chr(b)
        out.append(c if c.isalnum() and b < 128 else "\\x%02x" % b)
    return '"' + "".join(out) + '"'


def pack_ranges(ranges):
    data = bytearray()
    for lo, hi, stride in ranges:
        data += lo.to_bytes(3, "little") + hi.to_bytes(3, "little") + stride.to_bytes(2, "little")
    return bytes(data)


def pack_cases(cases):
    data = bytearray()
    for lo, hi, a, b, c in cases:
        data += lo.to_bytes(3, "little") + hi.to_bytes(3, "little")
        for d in (a, b, c):
            data += (d & 0xFFFFFFFF).to_bytes(4, "little")
    return bytes(data)


def pack_orbit(orbit):
    data = bytearray()
    for a, b in orbit:
        data += a.to_bytes(3, "little") + b.to_bytes(3, "little")
    return bytes(data)


def printable_runs(cats):
    cps = set()
    for name in ("L", "M", "N", "P", "S"):
        for lo, hi, stride in cats[name]:
            cps.update(range(lo, hi + 1, stride))
    runs = []
    for cp in sorted(cps):
        if runs and runs[-1][1] == cp - 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return runs


def write_printable(version, cats):
    runs = printable_runs(cats)
    data = bytearray()
    for lo, hi in runs:
        data += lo.to_bytes(3, "little") + hi.to_bytes(3, "little")
    w = ["// Code generated by tools/gen_unicode.py from Go's unicode/tables.go; DO NOT EDIT.", "",
         "// The runes Go's unicode.IsPrint accepts beyond the ASCII space, as merged runs of 6 bytes (low,",
         "// high: 3 bytes each, little endian), for %%q. Unicode %s." % version,
         "func rt_print_runs() str {", "\treturn %s" % literal(bytes(data)), "}", ""]
    open(OUT_PRINT, "w", encoding="utf-8").write("\n".join(w))
    return len(runs)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else default_source()
    version, cats, scripts, props, cases, orbit = parse(src)
    groups = [("category", cats), ("script", scripts), ("property", props)]
    seen = {}
    for kind, tabs in groups:
        for name in tabs:
            if name in seen:
                sys.exit("name %s is both a %s and a %s" % (name, seen[name], kind))
            seen[name] = kind
    w = []
    w.append("// Code generated by tools/gen_unicode.py from Go's unicode/tables.go; DO NOT EDIT.")
    w.append("")
    w.append("package glyph")
    w.append("")
    w.append("// UnicodeVersion is the version of the Unicode Character Database the tables come from.")
    w.append('const UnicodeVersion = "%s"' % version)
    w.append("")
    names = {kind: sorted(tabs) for kind, tabs in groups}
    w.append("// Table names a set of code points by Unicode's own name: a general category (Lu, Nd, P), a")
    w.append("// script (Latin, Han, Arabic) or a property (White_Space, Dash). Use it with Is.")
    w.append("type Table enum {")
    for kind, _ in groups:
        for name in names[kind]:
            w.append("\t%s" % name)
    w.append("}")
    w.append("")
    w.append("// tableData returns the packed ranges of t: 8 bytes each (low, high, stride).")
    w.append("func tableData(t Table) str {")
    w.append("\tswitch t {")
    for kind, tabs in groups:
        for name in names[kind]:
            w.append("\tcase %s:" % name)
            w.append("\t\treturn t_%s" % name)
    w.append("\t}")
    w.append('\treturn ""')
    w.append("}")
    w.append("")
    for kind, tabs in groups:
        for name in names[kind]:
            w.append("const t_%s = %s" % (name, literal(pack_ranges(tabs[name]))))
    w.append("")
    w.append("// caseData holds Go's CaseRanges: low, high (3 bytes each) and the deltas to upper, lower and title")
    w.append("// case (4 bytes each, signed; 0x110000 means the upper/lower alternation).")
    w.append("const caseData = %s" % literal(pack_cases(cases)))
    w.append("")
    w.append("// orbitData holds Go's caseOrbit: pairs (3 bytes each) of a code point and the next one in its")
    w.append("// simple case-folding orbit.")
    w.append("const orbitData = %s" % literal(pack_orbit(orbit)))
    w.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(w))
    nruns = write_printable(version, cats)
    print("%s: %d printable runs" % (OUT_PRINT, nruns))
    print("%s: %d tables, %d case ranges, %d orbit pairs, Unicode %s" % (
        OUT, len(seen), len(cases), len(orbit), version))


if __name__ == "__main__":
    main()
